# Generated by Django 3.2.12 on 2022-02-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biom',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 's284720.mode',
            },
        ),
    ]
